services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: dev
      args:
        - APP_NAME=api
    command: pnpm --filter api run start
#    command: tail -f /dev/null
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/api:/app/apps/api
      - /app/node_modules
      - /app/apps/api/node_modules
    networks:
      - app-network

  # Docker shared network definition
networks:
  app-network:
    driver: bridge